name: Node Documentation CI/CD
on:
  push:
    branches: 
      - main
        
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CreatorNodeDocumentation

    steps: 
    - name: Checkout source
      uses: actions/checkout@v3

    - uses: actions-rs/cargo@v1

    - name: Install mdBook
      run: cargo install mdbook

    - name: Build mdBook
      run: |
        mdbook build
        cat book/concepts/GeneralConcepts/nurbsCurve.html

    - name: Dump Github Context
      run: |
        echo ref: '${{ github.ref }}'
        echo sha: '${{ github.sha }}'
        echo event-name: '${{ github.event_name }}'
        echo run-number: '${{ github.run_number }}'
      