name: Node Documentation CI/CD
on:
  push:
    branches: 
      - main
        
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CreatorNodeDocumentation
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps: 
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Dump Github Context
      run: |
        echo github.workflow: '${{ github.workflow }}'
        echo ref: '${{ github.ref }}'
        echo sha: '${{ github.sha }}'
        echo event-name: '${{ github.event_name }}'
        echo run-number: '${{ github.run_number }}'

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Build mdBook
      run: |
        echo Using $(mdbook --version)
        mdbook build

    - name: Archive build files
      uses: actions/upload-artifact@v3
      with:
        name: book
        path: |
          CreatorNodeDocumentation/book
        retention-days: 1
      